// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4-_euVuxMBV6c1KRJa4cx4SG1t82jV8',
    appId: '1:849753893490:web:bb2f0bbca80e651893f0eb',
    messagingSenderId: '849753893490',
    projectId: 'mynotes-kvcet-21a10',
    authDomain: 'mynotes-kvcet-21a10.firebaseapp.com',
    storageBucket: 'mynotes-kvcet-21a10.appspot.com',
    measurementId: 'G-S07EJJ8T8W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw7sl94AkcxmJT3rnla4qnZV8K6gn2yvU',
    appId: '1:849753893490:android:f98053c0ff51267593f0eb',
    messagingSenderId: '849753893490',
    projectId: 'mynotes-kvcet-21a10',
    storageBucket: 'mynotes-kvcet-21a10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4wM8U5LQn5-Lq855Pi17j_umblgKhPvo',
    appId: '1:849753893490:ios:145d3137451726ba93f0eb',
    messagingSenderId: '849753893490',
    projectId: 'mynotes-kvcet-21a10',
    storageBucket: 'mynotes-kvcet-21a10.appspot.com',
    iosClientId: '849753893490-qmv1cgn2a27pum0ingk263a97gosu5vl.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4wM8U5LQn5-Lq855Pi17j_umblgKhPvo',
    appId: '1:849753893490:ios:99cdb61266b54a4d93f0eb',
    messagingSenderId: '849753893490',
    projectId: 'mynotes-kvcet-21a10',
    storageBucket: 'mynotes-kvcet-21a10.appspot.com',
    iosClientId: '849753893490-nq4006268cnsqtbrequb5qjb40e9akmr.apps.googleusercontent.com',
    iosBundleId: 'kvcet.cse.mynotes',
  );
}
